swagger: "2.0"
info:
  version: "0.0.1"
  title: UserAPI
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /users:
    x-swagger-router-controller: Users
    get:
      operationId: getAll
      description: Get all users
      responses:
        "200":
          description: Return list of users
          schema:
            $ref: "#/definitions/UsersListResponse"
        default:
          description: User list cannot be loaded
          schema:
            $ref: "#/definitions/StatusResponse"
    post:
      operationId: create
      description: Register new user
      parameters:
        - name: User
          description: User properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/UserInput"
      responses:
        "200":
          description: User saved
          schema:
            $ref: "#/definitions/StatusResponse"
        default:
          description: User cannot be saved
          schema:
            $ref: "#/definitions/StatusResponse"
  /users/{id}:
    x-swagger-router-controller: Users
    get:
      operationId: find
      description: Get an user
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Return User
          schema:
            $ref: "#/definitions/User"
        default:
          description: User not found
          schema:
            $ref: "#/definitions/StatusResponse"
    put:
      operationId: update
      description: Update User
      parameters:
        - name: id
          type: string
          in: path
          required: true
        - name: user
          description: User properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/UserInput"
      responses:
        "200":
          description: User updated
          schema:
            $ref: "#/definitions/StatusResponse"
        default:
          description: User cannot be updated
          schema:
            $ref: "#/definitions/StatusResponse"
    delete:
      operationId: delete
      description: Delete user
      parameters:
        - name: id
          description: User ID
          type: string
          in: path
          required: true
      responses:
        "200":
          description: User deleted
          schema:
            $ref: "#/definitions/StatusResponse"
        default:
          description: User cannot be deleted
          schema:
            $ref: "#/definitions/StatusResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  User:
    type: object
    properties:
      id:
        type: string
      email:
        type: string
        format: email
      forename:
        type: string
      surname:
        type: string
      created:
        type: string
        format: date-time
    required:
      - id
      - email
      - created
      
  UserInput:
    type: object
    properties:
      email:
        type: string
        format: email
      forename:
        type: string
      surname:
        type: string
    required:
      - email
    
  UsersListResponse:
    properties:
      users:
        type: array
        items:
          $ref: "#/definitions/User"
    required:
      - users
  
  StatusResponse:
    type: object
    properties:
      message:
        type: string
        description: Status message
    required:
      - message